#!/bin/bash
if [ $# -lt 1 ]; then
    echo "Usage: $0 <hostname>" >&2
    echo "  e.g. $0 chop.aaron.dyn.iweb.co.uk" >&2
    exit 1
fi
i=$1
rm -rf cc
httrack -O cc http://$i/
cd cc/$i
git init
git add .
git commit -m 'Website'
git push git@github.com:getchopchop/getchopchop.github.io master:master -f
